--Optimised VMT SQL
drop table if exists tmp_vicmap_transport;
drop table if exists tmp_vicmap_transport_attribute;

with tmp_vicmap1 as (
  select
    ST_GeomFromGeoJSON("geometry") as geom_feature,
    "road_name",
    "feature_type_code", 
    "class_code", 
    "height_limit",
    "id",
    "Shape__Length",
    "construction_material",
    "construction_type",
    "coordinating_auth_code",
    "create_date_pfi",
    "create_date_ufi",
    "deck_area",
    "direction_code",
    "div_rd",
    "ezi_road_name" as local_road,
    "ezi_road_name_label",
    "feature_quality_id",
    "from_ufi",
    "left_locality",
    "length_m",
    "load_limit",
    "load_limit_assess_date",
    "named_feature_id",
    "nre_route",
    "pfi",
    "physical_condition",
    "responsible_auth_code",
    "restrictions",
    "right_locality",
    "road_name_1",
    "road_name_2",
    "road_name_3",
    "road_name_4",
    "road_name_5",
    "road_name_6",
    "road_name_7",
    CASE
    	WHEN "road_name_1" IS NULL AND "road_type_1" IS NULL AND "road_suffix_1" IS NULL THEN NULL
    	ELSE COALESCE("road_name_1", '') || ' ' || COALESCE("road_type_1", '') || ' ' || COALESCE("road_suffix_1", '')
	END AS alternative_road_1,
	CASE
    	WHEN "road_name_2" IS NULL AND "road_type_2" IS NULL AND "road_suffix_2" IS NULL THEN NULL
    	ELSE COALESCE("road_name_2", '') || ' ' || COALESCE("road_type_2", '') || ' ' || COALESCE("road_suffix_2", '')
	END AS alternative_road_2,
	CASE
    	WHEN "road_name_3" IS NULL AND "road_type_3" IS NULL AND "road_suffix_3" IS NULL THEN NULL
    	ELSE COALESCE("road_name_3", '') || ' ' || COALESCE("road_type_3", '') || ' ' || COALESCE("road_suffix_3", '')
	END AS alternative_road_3,
    "road_name_use",
    "road_name_use_1",
    "road_name_use_2",
    "road_name_use_3",
    "road_name_use_4",
    "road_name_use_5",
    "road_name_use_6",
    "road_name_use_7",
    "road_seal",
    "road_status",
    "road_suffix",
    "road_suffix_1",
    "road_suffix_2",
    "road_suffix_3",
    "road_suffix_4",
    "road_suffix_5",
    "road_suffix_6",
    "road_suffix_7",
    "road_type",
    "road_type_1",
    "road_type_2",
    "road_type_3",
    "road_type_4",
    "road_type_5",
    "road_type_6",
    "road_type_7",
    "route_no",
    "seasonal_close_date",
    "seasonal_open_date",
    "structure_name",
    "superceded_pfi",
    "task_id",
    "to_ufi",
    "ufi",
    "urban",
    "vehicular_access",
    "width_m"
  from map_manager.stg_vicmap_transport
)
select
  'VICMAP_TRANSPORT&&'|| "ufi" as feature_id,  -- Maybe generate from s_source_id when we get this
  "road_name" as s_name,
  geom_feature,
  "road_name",
  "id",
  "feature_type_code",
  "class_code",
  "height_limit",
  "id" as s_source_id,
  "Shape__Length",
  "construction_material",
  "construction_type",
  "coordinating_auth_code",
  "create_date_pfi",
  "create_date_ufi",
  "deck_area",
  "direction_code",
  "div_rd",
  local_road,
  "ezi_road_name_label",
  "feature_quality_id",
  "from_ufi",
  "left_locality",
  "length_m",
  "load_limit",
  "load_limit_assess_date",
  "named_feature_id",
  "nre_route",
  "pfi",
  "physical_condition",
  "responsible_auth_code",
  "restrictions",
  "right_locality",
  "road_name_1",
  "road_name_2",
  "road_name_3",
  "road_name_4",
  "road_name_5",
  "road_name_6",
  "road_name_7",
  alternative_road_1,
  alternative_road_2,
  alternative_road_3,
  "road_name_use",
  "road_name_use_1",
  "road_name_use_2",
  "road_name_use_3",
  "road_name_use_4",
  "road_name_use_5",
  "road_name_use_6",
  "road_name_use_7",
  "road_seal",
  "road_status",
  "road_suffix",
  "road_suffix_1",
  "road_suffix_2",
  "road_suffix_3",
  "road_suffix_4",
  "road_suffix_5",
  "road_suffix_6",
  "road_suffix_7",
  "road_type",
  "road_type_1",
  "road_type_2",
  "road_type_3",
  "road_type_4",
  "road_type_5",
  "road_type_6",
  "road_type_7",
  "route_no",
  "seasonal_close_date",
  "seasonal_open_date",
  "structure_name",
  "superceded_pfi",
  "task_id",
  "to_ufi",
  "ufi",
  "urban",
  "vehicular_access",
  "width_m"
into temporary tmp_vicmap_transport
from tmp_vicmap1
;

with tmp_attribute_fields as (
  select
    array[
  'road_name',
  'road_number',
  'feature_type_code',
  'class_code',
  'height_limit',
  'Shape__Length',
  'construction_material',
  'construction_type',
  'coordinating_auth_code',
  'create_date_pfi',
  'create_date_ufi',
  'deck_area',
  'direction_code',
  'div_rd',
  'local_road',
  'ezi_road_name_label',
  'feature_quality_id',
  'from_ufi',
  'left_locality',
  'length_m',
  'load_limit',
  'load_limit_assess_date',
  'named_feature_id',
  'nre_route',
  'pfi',
  'physical_condition',
  'responsible_auth_code',
  'restrictions',
  'right_locality',
  'road_name_1',
  'road_name_2',
  'road_name_3',
  'road_name_4',
  'road_name_5',
  'road_name_6',
  'road_name_7',
  'alternative_road_1',
  'alternative_road_2',
  'alternative_road_3',
  'road_name_use',
  'road_name_use_1',
  'road_name_use_2',
  'road_name_use_3',
  'road_name_use_4',
  'road_name_use_5',
  'road_name_use_6',
  'road_name_use_7',
  'road_seal',
  'road_status',
  'road_suffix',
  'road_suffix_1',
  'road_suffix_2',
  'road_suffix_3',
  'road_suffix_4',
  'road_suffix_5',
  'road_suffix_6',
  'road_suffix_7',
  'road_type',
  'road_type_1',
  'road_type_2',
  'road_type_3',
  'road_type_4',
  'road_type_5',
  'road_type_6',
  'road_type_7',
  'route_no',
  'seasonal_close_date',
  'seasonal_open_date',
  'structure_name',
  'superceded_pfi',
  'task_id',
  'to_ufi',
  'ufi',
  'urban',
  'vehicular_access',
  'width_m'
  ] as attribute_fields
), tmp_vicmap2 as (
  select
    unnest(array(select feature_id || '&&' || (unnest(attribute_fields)))) as attribute_id,
    feature_id,
    unnest(attribute_fields) as s_name,
    unnest(array[
    "road_name",
    "id",
    "feature_type_code",
    "class_code",
    "height_limit",
    "Shape__Length",
    "construction_material",
    "construction_type",
    "coordinating_auth_code",
    "create_date_pfi",
    "create_date_ufi",
    "deck_area",
    "direction_code",
    "div_rd",
    "local_road",
    "ezi_road_name_label",
    "feature_quality_id",
    "from_ufi",
    "left_locality",
    "length_m",
    "load_limit",
    "load_limit_assess_date",
    "named_feature_id",
    "nre_route",
    "pfi",
    "physical_condition",
    "responsible_auth_code",
    "restrictions",
    "right_locality",
    "road_name_1",
    "road_name_2",
    "road_name_3",
    "road_name_4",
    "road_name_5",
    "road_name_6",
    "road_name_7",
    "alternative_road_1",
	  "alternative_road_2",
	  "alternative_road_3",
    "road_name_use",
    "road_name_use_1",
    "road_name_use_2",
    "road_name_use_3",
    "road_name_use_4",
    "road_name_use_5",
    "road_name_use_6",
    "road_name_use_7",
    "road_seal",
    "road_status",
    "road_suffix",
    "road_suffix_1",
    "road_suffix_2",
    "road_suffix_3",
    "road_suffix_4",
    "road_suffix_5",
    "road_suffix_6",
    "road_suffix_7",
    "road_type",
    "road_type_1",
    "road_type_2",
    "road_type_3",
    "road_type_4",
    "road_type_5",
    "road_type_6",
    "road_type_7",
    "route_no",
    "seasonal_close_date",
    "seasonal_open_date",
    "structure_name",
    "superceded_pfi",
    "task_id",
    "to_ufi",
    "ufi",
    "urban",
    "vehicular_access",
    "width_m"]) as s_value
   from tmp_vicmap_transport, tmp_attribute_fields
)
select
  attribute_id,
  feature_id,
  s_name,
  s_value
into temporary tmp_vicmap_transport_attribute
from tmp_vicmap2
;

-- mm_layer
insert into map_manager.mm_layer
select
  'VICMAP_TRANSPORT' as layer_id,
  'VicMap Transport' as s_name,
  'LINE' as e_layer_type
on conflict (layer_id) do update
set
  layer_id = excluded.layer_id,
  s_name = excluded.s_name,
  e_layer_type = excluded.e_layer_type
;

-- mm_feature
insert into map_manager.mm_feature (
  feature_id,
  layer_id,
  s_name,
  e_feature_type,
  s_source_id,
  geom_feature,
  changeset_id,
  global_version_id_start,
  join_key
)
select
  feature_id,
  'VICMAP_TRANSPORT' as layer_id,
  s_name,
  'LINE' as e_feature_type,
  s_source_id,
  geom_feature,
  'INITIAL_CHANGESET' as changeset_id, 
  0 as global_version_id_start,
  MD5(coalesce(s_name, '') || coalesce(ufi, '') || coalesce(st_astext(geom_feature), '')) as join_key
from tmp_vicmap_transport
on conflict (feature_id, changeset_id) do update
set
  feature_id = excluded.feature_id,
  layer_id = excluded.layer_id,
  s_name = excluded.s_name,
  e_feature_type = excluded.e_feature_type,
  s_source_id = excluded.s_source_id,
  geom_feature = excluded.geom_feature,
  changeset_id = excluded.changeset_id,
  global_version_id_start = excluded.global_version_id_start,
  join_key = excluded.join_key
;

-- mm_attribute
insert into map_manager.mm_attribute (
  attribute_id,
  feature_id,
  s_name,
  s_value,
  changeset_id,
  global_version_id_start,
  join_key
)
select
  attribute_id,
  feature_id,
  s_name,
  s_value,
  'INITIAL_CHANGESET' as changeset_id,
  0 as global_version_id_start, 
  MD5(coalesce(feature_id, '') || coalesce(s_name, '') || coalesce(s_value, '')) as join_key
from tmp_vicmap_transport_attribute where s_value is not null
on conflict (attribute_id, changeset_id) do update
set
  attribute_id = excluded.attribute_id,
  feature_id = excluded.feature_id,
  s_name = excluded.s_name,
  s_value = excluded.s_value,
  changeset_id = excluded.changeset_id,
  global_version_id_start = excluded.global_version_id_start,
  join_key = excluded.join_key
;

