**/*.csv
**/*.osm
**/*.json
**/*.jld2
**/*.so
**/*.zip
**/Manifest.toml

Dockerfile
DockerfileBuildTest
Makefile
README.md
azure-pipelines.yaml
chart/
docker-compose.yaml

!MapExporter.so
!Manifest.toml