from pathlib import Path
import json


def generate_title(name, app_dir):
    readme = Path(app_dir, "README.md")
    with readme.open("w") as file:
        file.write(f"# {snake_to_title(name)}\n")


def generate_version_used(app_dir):
    version_path = Path(__file__).parent.parent
    version_data = json.load(Path(version_path, "pkg_info.json").open("r"))

    readme_str = f"""
## Template Version Used
This README and the base level folder structure were generated by the OR-SDK for Python: `v{version_data['version']}`\
"""
    open_readme_and_append(app_dir, readme_str)


def generate_microservice_readme_body(name, app_dir):
    """Build a standard microservice readme body for the `README.md` in the app_dir, for the provided app name."""
    generate_overview_header(name, app_dir)
    generate_microservice_requirements(name, app_dir)
    generate_file_structure_placeholder(name, app_dir, type="Microservice")
    generate_more_information(name, app_dir)


def generate_library_readme_body(name, app_dir):
    """Build a standard library readme body for the `README.md` in the app_dir, for the provided app name."""
    generate_overview_header(name, app_dir)
    generate_library_requirements(name, app_dir)
    generate_file_structure_placeholder(name, app_dir, type="Library")
    generate_library_install(name, app_dir)
    generate_more_information(name, app_dir)


def generate_overview_header(name, app_dir):
    open_readme_and_append(app_dir, f"## {snake_to_title(name)} Overview\n")


def generate_microservice_requirements(name, app_dir):
    readme_str = f"""\
### Microservice Requirements
This microservice follows a standardised structure for microservice deployment, and is based on an
asynchronous web-app structure that is used throughout the Optimal Reality ecosystem.

It contains the following items:
- `{snake_to_title(name)}` folder containing the application code.
- `tests` folder to contain any unit and system tests that the microservice may require.
- `requirements*.txt` files to control required files. The standard `requirements.txt` should be used \
for any non-or packages that are used by the microservice, `requirements-libs.txt` is for OR \
specific libraries available through the extended pip interface, and others are required \
for deployements, artefacts, etc.
- `pkg_version.json` for tracking the current semantic version of the microservice.
- `Makefile`, `Dockerfile`, `docker-compose.yaml`, and `azure-pipelines.yaml` examples.

"""
    open_readme_and_append(app_dir, readme_str)


def generate_library_requirements(name, app_dir):
    readme_str = f"""\
### Library Requirements
This library follows a standardised structure for library deployment, and is based on an
a simple library structure that is used throughout the Optimal Reality ecosystem.

It contains the following items:
- `{snake_to_title(name)}` folder containing the application code.
- `tests` folder to contain any unit and system tests that the microservice may require.
- `requirements*.txt` files to control required files. The standard `requirements.txt` should be used \
for any non-or packages that are used by the microservice, `requirements-libs.txt` is for OR \
specific libraries available through the extended pip interface, and others are required \
for deployements, artefacts, etc.
- `pkg_version.json` for tracking the current semantic version of the microservice.
- `setup.py` which will be used to build the library as a package that can be used in python.

- `Makefile`, and `azure-pipelines.yaml` examples.
"""
    open_readme_and_append(app_dir, readme_str)


def generate_file_structure_placeholder(name, app_dir, type="**DEFAULT TYPE**"):
    readme_str = f"""\
### {type} Structure
The following files make up the body of the {snake_to_title(name)} codebase:
- `{name}`
    - **TBC**
- **TBC**
- `utilities`
    - `decotrators`
    - `log_utils`
    - logging.yaml

"""
    open_readme_and_append(app_dir, readme_str)


def generate_library_install(name, app_dir):
    readme_str = f"""\
## How to install
To install this package, please see [OR Python Libraries][core_connect_to_python_libraries] for the connection details and process.

[core_connect_to_python_libraries]: https://hub.deloittedigital.com.au/wiki/display/CORE/OR+Python+Libraries
"""
    open_readme_and_append(app_dir, readme_str)


def generate_more_information(name, app_dir):
    readme_str = f"""\
## More Information
For more information, please see [{snake_to_title(name)}][core_documentation_link].

[core_documentation_link]: 
"""
    open_readme_and_append(app_dir, readme_str)


## UTILITIES FUNCITONS
def open_readme_and_append(app_dir, string:str):
    """Opens the `README.md` markdown file in the app_dir provided, and appends the string to that file."""
    readme = Path(app_dir, "README.md")
    with readme.open("a") as file:
        file.write(string)


def snake_to_title(string:str):
    """Convert a string from `snake_case` or `SCREAMING_SNAKE_CASE` to `Title Case`."""
    return string.replace("_", " ").title()


## MAIN BUILD
if __name__=="__main__":
    app_dir = Path.cwd()
    name = "python_app_template"
    generate_title(name, app_dir)
    generate_microservice_readme_body(f"{name}_microservice", app_dir)
    generate_library_readme_body(f"{name}_library", app_dir)
    generate_version_used(app_dir)