"""
    multi_replace(string::AbstractString, multipair_replace::AbstractVector{Pair{String, String}})

Recursively apply the replace function to the string, applying the pairs from first to last in the provided vector.
"""
multi_replace(string::AbstractString, multipair_replace::AbstractVector) = _multi_replace(string, multipair_replace, length(multipair_replace))


"""
    _multi_replace(string::AbstractString, multipair_replace::AbstractVector, multipair_length::Int)

Recursively apply the replace function to the string, applying the pairs from first to last in the provided vector, based on an indexing length.
This is used by `multi_replace`, and should not be accessed directly otherwise.
"""
function _multi_replace(string::AbstractString, multipair_replace::AbstractVector, multipair_length::Int)
    if multipair_length == 0
        return string
    end
    apply_index = length(multipair_replace) - multipair_length + 1
    return _multi_replace(replace(string, multipair_replace[apply_index]), multipair_replace, multipair_length-1)
end


"""
    dollar_marked_values(array_like)

Creates a joined string of the values in array_like, with a \$ preceding each value.

```
dollar_marked_values([1, 2, 3])
>>> "(\$1, \$2, \$3)"
```
"""
dollar_marked_values(array_like) = "(\$" * join(array_like, ", \$") * ")"


"""
get_value_str(value::String)
get_value_str(value)

Converts the value into a string, unless it is already a string in which case it is 
prepended and appended with `'`.
"""
get_value_str(value::String) = "'" * value * "'"
get_value_str(value) = string(value)

"""
    get_unique_name(name::U, taken_names::AbstractVector{U}) where U<:AbstractString

Checks that the name is unique in the provided list of names. If it's not, a new name
is generated by appending a number up to 10,000. If this threshold is reached, then a
uuid4 unique string is appended instead.
"""
function get_unique_name(name::U, taken_names::AbstractVector{U}) where U<:AbstractString
    if name ∉ taken_names
        return name
    end
    i = 1
    while i < 10000
        new_name = "$(name)_$(i)"
        if new_name ∉ taken_names
            return new_name
        end
    end
    uuid = uuid4().value
    return "$(name)_$(uuid)"
end

"""
    snake_to_camel(str::AbstractString)

Converts snake case to camel case.
"""
function snake_to_camel(str::AbstractString)
    camel_str = join(uppercasefirst.(split(str, "_")))
    return lowercase(camel_str[1]) * camel_str[2:end]
end

"""
Current unix epoch time
"""
current_time() = floor(Int, time())

"""
    _generate_column_line(column_name::AbstractString, column_metadata::AbstractDict{String, Any})

Generates a column definition for the table, based on the column name and the provided metadata for that column.

Column Metadata must be a dictionary, and requires the type to be provided. The total fields are:
1. *type*: SQL type, with or without size, as a string. **This is always required.**
1. *length*: SQL type's length, as a string or integer.
1. *check*: SQL check for the column, as a string, which should return a boolean when run.
1. *not_null*: If included and `true`, the column will be set to NOT NULL.
1. *unique*: If included and `true`, the column will be set to UNIQUE.
1. *primary_key*: If included and `true`, the column will be set to be the PRIMARY KEY
"""
function _generate_column_line(column_name::AbstractString, column_metadata::AbstractDict)
    if !haskey(column_metadata, "type")
        throw(PSQLInterfaceException("All column definitions require a type."))
    end
    type_length = haskey(column_metadata, "length") ? " ($(column_metadata["length"]))" : ""
    check = haskey(column_metadata, "check") ? " CHECK ($(column_metadata["check"]))" : ""
    not_null = get(column_metadata, "not_null", false) ? " NOT NULL" : ""
    unique = get(column_metadata, "unique", false) ? " UNIQUE" : ""
    primary = get(column_metadata, "primary_key", false) ? " PRIMARY KEY" : ""
    return "$(column_name) $(uppercase(column_metadata["type"]))$(type_length)$(unique)$(primary)$(not_null)$(check)"
end


"""
    _delimit_object_names(str::String)

Private method for delimiting object names, such as tables, schemas, and column headers. Required for `camelCase` or any
capitalisation to work correctly. This assumes that your string is splitablle on `.` and will rejoin on this delimiter.
"""
function _delimit_object_names(str::AbstractString)
    return join(map(x -> first(x) == '\"' ? x : '\"'*x*'\"', split(str, ".")), ".")
end