apiVersion: v1
kind: Service
metadata:
  name: {{ include "map-exporter-service.name" . }}
  labels:
    {{- include "map-exporter-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "map-exporter-service.selectorLabels" . | nindent 4 }}
